{% set version = '0.5-1' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-registry
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/registry_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/registry/registry_{{ version }}.tar.gz
  sha256: dfea36edb0a703ec57e111016789b47a1ba21d9c8ff30672555c81327a3372cc

build:
  merge_build_host: True  # [win]
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('registry')"           # [not win]
    - "\"%R%\" -e \"library('registry')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=registry
  license: GPL-2
  summary: Provides a generic infrastructure for creating and using registries.
  license_family: GPL2
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: registry
# Type: Package
# Title: Infrastructure for R Package Registries
# Version: 0.5-1
# Author: David Meyer
# Maintainer: David Meyer <David.Meyer@R-project.org>
# Description: Provides a generic infrastructure for creating and using registries.
# Depends: R (>= 2.6.0)
# Imports: utils
# License: GPL-2
# NeedsCompilation: no
# Packaged: 2019-03-05 12:35:44 UTC; meyer
# Repository: CRAN
# Date/Publication: 2019-03-05 14:21:41 UTC
