{% set version = "0.5" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-registry
  version: {{ version|replace("-", "_") }}

source:
  fn: registry_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/registry_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/registry/registry_{{ version }}.tar.gz

  sha256: 5d8be59ba791987b2400e9e8eaaac614cd544c1aece785ec4782ea6d5ea00efb

build:
  number: 0
  skip: true  # [win32]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base

  run:
    - r-base

test:
  commands:
    - $R -e "library('registry')"  # [not win]
    - "\"%R%\" -e \"library('registry')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=registry
  license: GPL 2.0
  license_family: GPL
  summary: Provides a generic infrastructure for creating and using registries.

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
