appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: gLSWYon//yKsEPIuP1nyyG542Wt+px4ULrIaHSgtXm1Z1XOxaW2SGUo0Cl4+6KJbC6DJFL+GbsML5B5fk+8HosC29MH1OB8h1WoP9n79d247Dma1o1YkzGkcJR1PRQrbmd1iqaN7fyuIbSz04aGbz4ygpHtlAG28WcHy8b6pvu8EcMl2JprtuIUdNcRZHfZhsJjobUWmn4KhT1SfCjZxT/+F6spT50GuEo5CvTKgAxoz3FLT1MfxkHUaN25bNNLuEhs9EtZCuMx1025p1oF1OrZWlNh5Xozw8MQ6wVuxzqteHcRPHVR4S35OA+ud2JajgKJRTxJwbzlXTvcc3s9t7lWDrJMOA/sDFNGmiV+i0/IR/K/7C7gKLN39sqqnte76n/PmicuLejOigR7ffbGM2dZoh86t8oqyjdqj51ezLPdR91BkBb42371j9N6wtv11OknJlHY8+Td7GX/W3ctFaPVBHc/6Wkdd/0kcr/fM8RqDIkSZUW9VsWV5t2yudDYU1PgRdU13RVGoV6DrBXd6aVYgJka61ItKMGjqBeiBnHX4FTwCEZTS3Awmug0uptP6UymmrFow+jJwSVaiSZfuSu7EqgTGPsY8MijHo1JTXPX47+aHcJDS28Hxgb3mK8NA0/vpmrqnvPbyVxQUcbQRpEX/7eBXYQSai2bAKsRNooI=
